spring:
  datasource:
    url: jdbc:mysql://47.102.203.94:3306/test?serverTimezone=UTC&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 3
      auto-commit: true
      idle-timeout: 60000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      maximum-pool-size: 10
      connection-test-query: SELECT 1
    driver-class-name: com.mysql.cj.jdbc.Driver